minor

diff --git a/bin/geomview/geomview b/bin/geomview/geomview
--- a/bin/geomview/geomview
+++ b/bin/geomview/geomview
@@ -13,26 +13,62 @@ usg () {
 : ${WX=800}
 : ${WY=600}
 
+num0 () { "$AWK" -v n="$1" 'BEGIN  {r = !(n + 0 == n); exit r }'; }
+num () { if ! num0 "$1"; then err "not a number '$1'"; fi; }
+
+off0() {
+    test -f "$1" &&
+	"$AWK" '{ if ("" $0 ~ /OFF/) exit 0; else exit 1 }' "$1"
+}
+off()  { if ! off0 "$1"; then err "not an off file '$1'"; fi; }
+
+filep() { if test ! -f "$1"; then err "not a file '$1'"; fi; }
+
 if test $# -ne 0 && test "$1" = -h; then usg; fi
+if ! e "$GEOMVIEW" --version '2>/dev/null' '1>/dev/null'; then err "$GEOMVIEW is not found"; fi
 
-off="$1"; shift
-
-if ! e "$GEOMVIEW" --version '2>/dev/null' '1>/dev/null'
-then err "$GEOMVIEW is not found"
-fi
+tx=0 ty=0 tz=0 rx=0 ry=0 rz=0 off= output= appearance=
+while test $# -ne 0
+do a="$1"; shift
+   case "$a" in
+       -t) if test $# -le 2; then err '-t needs three numbers'; fi
+	   num "$1"; tx="$1"; shift
+	   num "$1"; ty="$1"; shift
+	   num "$1"; tz="$1"; shift
+	   ;;
+       -r) if test $# -le 2; then err '-r needs three numbers'; fi
+	   num "$1"; rx="$1"; shift
+	   num "$1"; ry="$1"; shift
+	   num "$1"; rz="$1"; shift
+	   ;;
+       -o) if test $# -le 1; then err '-o needs a file'; fi
+	   output="$1"; shift
+	   ;;
+       -a) if test $# -le 1; then err '-o needs a file'; fi
+	   filep "$1"; appearance="$1"; shift
+	   ;;
+       -*) err "unknown option '$a'" ;;
+       *) off "$a"; off="$a"; shift ;;
+   esac
+done
+if test -z "$off"; then err 'off file is not given'; fi
 
 t=/tmp/geomview.$$
 trap 'e rm $t; exit 2' 1 2 3 4 15
 
-cat >$t <<!
-{ appearance {
-      +edge
-      material { ks 0.0 }
-  }
+if test -z "$appearance"
+then appearance="+edge material { ks 0.0 }"
+else appearance="`cat "$appearance"`"
+fi
+
+cat > $t <<!
+{
+  appearance { $appearance }
   < "$off"
 }
 !
 
-e "$GEOMVIEW" -wpos $WX,$WY -noinit -nopanels -b 1 1 1 -run "$prog0" $t
+"$GEOMVIEW" -wpos $WX,$WY -noinit -nopanels -b 1 1 1 -run \
+  "$prog0" $t \"$tx $ty $tz\"  \"$rx $ry $rz\" "$output"
 
 rm -f $t
