upd host

diff --git a/bin/run/run b/bin/run/run
--- a/bin/run/run
+++ b/bin/run/run
@@ -31,6 +31,7 @@ if test $# -eq 0
 then err "'prog' is missing"; fi
 
 e export OMP_NUM_THREADS=$NT
+for i; do shift; set -- "$@" "`quote "$i"`"; done
 if test ! -z "${VAL+x}"
 then
     e "$VALGRIND" "$VAL" "$@"
@@ -41,13 +42,16 @@ elif test ! -z "${GDB+x}"
 then
     gdb0 "$@"
 else
-    if test "$host" = euler
-    then
-        if ! "$BSUB" -V 2>/dev/null; then err "$BSUB is not found"; fi
-	for i; do shift; set -- "$@" "`quote "$i"`"; done
-	if test $? -ne 0; then err 'fail to load module gsl'; fi
-	e $BSUB -n $NT $CO_ARG "$@"
-    else
-	e "$@"
-    fi
+    case "$host" in
+        euler)
+            if ! "$BSUB" -V 2>/dev/null; then err "$BSUB is not found"; fi
+            e $BSUB -n $NT $CO_ARG "$@"
+            ;;
+        falcon)
+            e module load gsl
+            if test $? -ne 0; then err 'fail to load module gsl'; fi
+            e "$@"
+            ;;
+        *) e "$@"
+    esac 
 fi
